name: yapzap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.11.0
  flutter_webrtc: ^0.9.22
  socket_io_client: ^2.0.0
  provider: ^6.0.5
  lottie: ^2.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/animation.json
    - assets/images/
    - assets/fonts/
