name: yapzap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.3 
  firebase_core: ^3.8.0 
  firebase_storage: ^12.3.6 
  cloud_firestore: ^5.5.0
  flutter_webrtc: ^0.9.22
  socket_io_client: ^2.0.0
  provider: ^6.0.5
  lottie: ^2.3.2
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.1
  permission_handler: ^10.4.1


  # provider_installer: ^1.0.1
  # firebase_storage: ^11.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/giphy.gif
    - assets/images/yapzap_logo.png
    - assets/fonts/

    

