// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyBqYL2zKT45vQFPbkOycdnILE_a8sUow',
    appId: '1:911343565754:web:7966892f42eb13f6ccfb83',
    messagingSenderId: '911343565754',
    projectId: 'chat-app-c360c',
    authDomain: 'chat-app-c360c.firebaseapp.com',
    storageBucket: 'chat-app-c360c.firebasestorage.app',
    measurementId: 'G-9DWJHMM327',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWm0a-u1Bpi2RnnBmQrJrfhDCvQzdqGAU',
    appId: '1:911343565754:android:241bdc5dc45d90f7ccfb83',
    messagingSenderId: '911343565754',
    projectId: 'chat-app-c360c',
    storageBucket: 'chat-app-c360c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCekEPvx18E9vzHDyM5f8gw004LmuHfx5M',
    appId: '1:911343565754:ios:87046c9b4e8445e7ccfb83',
    messagingSenderId: '911343565754',
    projectId: 'chat-app-c360c',
    storageBucket: 'chat-app-c360c.firebasestorage.app',
    androidClientId: '911343565754-3j1mgehfntue887vudpuqdokr6r6j14s.apps.googleusercontent.com',
    iosClientId: '911343565754-ej5u2u4llc1utfbol00ppep5njv8vfc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.yapzap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCekEPvx18E9vzHDyM5f8gw004LmuHfx5M',
    appId: '1:911343565754:ios:87046c9b4e8445e7ccfb83',
    messagingSenderId: '911343565754',
    projectId: 'chat-app-c360c',
    storageBucket: 'chat-app-c360c.firebasestorage.app',
    androidClientId: '911343565754-3j1mgehfntue887vudpuqdokr6r6j14s.apps.googleusercontent.com',
    iosClientId: '911343565754-ej5u2u4llc1utfbol00ppep5njv8vfc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.yapzap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyBqYL2zKT45vQFPbkOycdnILE_a8sUow',
    appId: '1:911343565754:web:07fa998b33d2ce81ccfb83',
    messagingSenderId: '911343565754',
    projectId: 'chat-app-c360c',
    authDomain: 'chat-app-c360c.firebaseapp.com',
    storageBucket: 'chat-app-c360c.firebasestorage.app',
    measurementId: 'G-56EBDCGM09',
  );
}
